on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Executing remote ssh command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH }}
          script: |
            echo "Stoping old version"
            if [ -d ~/base ];
            then
                cd ~/base
                make stop
            fi

            echo "Removing old version"
            cd ~
            rm -rf base
            # yes | sudo docker system prune -a

            echo "Pulling new version"
            GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git clone git@github.com:kosyachniy/base.git
            if [ -d ~/data ];
            then
                echo ""
            else
                mkdir data
            fi

            echo "Copying keys"
            cp ~/.secrets/base.env ~/base/.env

            echo "Starting new version"
            cd ~/base
            make run
